# This rule is not used by the project event-correlation-engine itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the correlation.dell.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: event-correlation-engine
    app.kubernetes.io/managed-by: kustomize
  name: dpceventgroup-editor-role
rules:
- apiGroups:
  - correlation.dell.com
  resources:
  - dpceventgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - correlation.dell.com
  resources:
  - dpceventgroups/status
  verbs:
  - get
